# install ubuntu
FROM ubuntu

# update repo
RUN apt update

# install python and flask
RUN apt install python3 python3-pip
RUN pip3 install Flask

# copy helloworld_httpserver.py
RUN mkdir /server
COPY ./helloworld_httpserver.py /server

# run the server
RUN cd /server && flask --app helloworld_httpserver run

# expose the server port
EXPOSE 80
